version: '3.9'

services:
  db:
    container_name: db

    image: mysql
    # restart: always
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carRental
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

